POST http://127.0.0.1/change HTTP/1.1
Content-Type: application/json
Content-Length: 57

{
    "username": "seokim",
    "password": "Root1006",
    "email": "test@test.com",
    "new_password" : "Root1007"
}